apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-app-sa
  namespace: pythonapp-dev
  annotations:
    # ⚠️ ACTION REQUIRED: Replace '123456789012' with your real AWS Account ID
    eks.amazonaws.com/role-arn: arn:aws:iam::668227158023:role/weather-app-pod-role 